title: Momentum
email: adammuman81@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A home for thoughts that build ideas that ship, and notes from the journey.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://adammomen.github.io" # the base hostname & protocol for your site

github_username: AdamMomen

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
